name: Update docker base image

## Update the base image every day
on:
  workflow_dispatch:
  schedule:
  ## In UTC
  - cron: '0 0 * * *'

## Build base images to be used by other github workflows
jobs:

  build:
    name: Update base Erlang/OTP build images
    if: github.repository == 'erlang/otp'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        type: [debian-base,ubuntu-base,i386-debian-base]

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Calculate BASE image
        id: base
        run: .github/scripts/base-tag "${{ matrix.type }}"
      - name: Build base image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/dockerfiles/Dockerfile.${{ steps.base.outputs.BASE_TYPE  }}
          pull: true
          build-args: BASE=${{ steps.base.outputs.BASE }}
          tags: docker.pkg.github.com/${{ github.repository }}/${{ matrix.type }}:latest
      - name: Push base image
        run: docker push docker.pkg.github.com/${{ github.repository }}/${{ matrix.type }}:latest
